config/routes.rb
TextApp::Application.routes.draw do
  root to: 'messages#index'
  resources :messages
  resources :contacts do
    resources :messages
  end


end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :phone_number, presence: true, numericality: true
  validates :phone_number, :length => { :in => 10..10}

end

app/models/message.rb
class Message < ActiveRecord::Base

  before_create :send_message

private

  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => {:To => to,
              :From => from,
              :Body => body }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end

  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Contact created"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

private
  def contact_params
    params.require(:contact).permit(:name, :phone_number)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
    if params[:contact_id] != nil
      @contact = Contact.find(params[:contact_id])
      @message[:to] = @contact.phone_number
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message has been sent"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private
  def message_params
    params.require(:message).permit(:to, :from, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %>
  <%= form.submit %>

<% end %>

app/views/contacts/index.html.erb
<h2>Contacts</h2>

<ul>
  <% @contacts.each do |contact| %>
  <li><%= link_to contact.name, contact %></li>
  <% end %>
</ul>

app/views/contacts/new.html.erb
<h2>New contact</h2>

<% if @contact.errors.any? %>
  <p>Please fix the following errors</p>
  <ul>
    <% @contact.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>


<%= render 'form' %>

app/views/contacts/show.html.erb
<h2> Name: <%= @contact.name %></h2>
<h2> Phone Number: <%= @contact.phone_number %></h2>

<%= link_to "Send #{@contact.name} a message", new_contact_message_path(@contact) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <p>Please fix the following errors</p>
  <ul>
    <li><%= object.errors.messages[:base] %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |form| %>
  <p><%= form.label :to %>
  <%= form.text_field :to %></p>
  <p><%= form.label :from %>
  <%= form.text_field :from %></p>
  <p><%= form.label :body %>
  <%= form.text_area :body %></p>
  <%= form.submit %>
<% end %>

app/views/messages/index.html.erb
<h2>All Messages</h2>

<ul>
  <% @messages.each do |m| %>
    <li><%= link_to "#{m.id}", message_path(m) %></li>
  <% end %>
</ul>

app/views/messages/new.html.erb
<h2>Create new message</h2>

<%= render '/layouts/errors', object: @message %>

<%= render 'form' %>

app/views/messages/show.html.erb
<h2>Sent message</h2>

<p>To: <%= @message.to %></p>
<p>From: <%= @message.from %></p>
<p>Body: <%= @message.body %></p>